### ISSUE TITLE
这效果模糊不说。。。

### ISSUE THREAD

**Issue by icemanyandy** [dream80/roop_colab#1]
这效果模糊不说。。。 头随便转个角度各种问题 。。。

**Comment by super-yan86** [comment]
确实，为什么那么模糊？

**Comment by destiny2408** [comment]
insightface的128的模型，其他都是套壳，不模糊才怪

**Comment by crj1998** [comment]
因为整个程序就是insightface加了个gui而已，不知道这种东西为什么有这么多star。看来门槛确实低了。

**Comment by dream80** [comment]
本质就是insightface，哈哈，所以说套壳很重要。我也觉得star多到离谱。
本质是简化之后受众多了，外加现在AI概念比较火，小视频啊，懂得不懂得都在发效果，关注度自然高了。

不过，从另外一个角度来说，谁觉得low，谁就搞个高级的啊。吐槽谁不会是吧。

坐等大佬们的512模型。

**Comment by dream80** [comment]
把issues当论坛没意义。
