### ISSUE TITLE
it's dangerous to teach people evade the NSFW fliter.

### ISSUE THREAD

**Issue by Moeblack** [dream80/roop_colab#2]
If you have figured it out, you should keep it to yourself - you don't know whether the person you are sharing it with is just a coomer or a psychopath who wants to ruin someone's life.
如果你已经搞清楚了，你应该自己保留 - 你不知道与你分享的人是一个仅仅是一个过度自慰者（Coomer）还是一个想要毁掉别人生活的精神变态。

**Comment by dream80** [comment]
Great suggestion, I think the word NSFW should be removed and Pornhub shut down。从此人们过上了无欲无求的幸福生活！

我并没有鼓励什么，我只是希望给大家选择的自由！
