### ISSUE TITLE
能否出一个打包成dmg安装包的教程呢

### ISSUE THREAD

**Issue by PuddingJoker** [dream80/roop_colab#3]
如题

**Comment by dream80** [comment]
这才是一个正常的issues。正在研究！

**Comment by PuddingJoker** [comment]
我最近在自己的m2mac上使用py2app打包，老是失败，恳请大佬研究研究，自己看的头都要炸了还没头绪

**Comment by PuddingJoker** [comment]
> 这才是一个正常的issues。正在研究！

楼主研究进度如何，我使用了py2app和pyinstaller都打包不成功
